name: Bug Report
description: Clearly report a bug with detailed repro steps
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **Thanks for your report!** Please check existing issues first:  
        👉 https://github.com/zgsm-ai/zgsm/issues

  - type: input
    id: version
    attributes:
      label: App Version
      description: What version of Shenma are you using? (e.g., v1.3.2)
    validations:
      required: true

  - type: dropdown
    id: provider
    attributes:
      label: API Provider
      options:
        - Zgsm
        - Anthropic
        - AWS Bedrock
        - Chutes AI
        - DeepSeek
        - Glama
        - Google Gemini
        - Google Vertex AI
        - Groq
        - Human Relay Provider
        - LiteLLM
        - LM Studio
        - Mistral AI
        - Ollama
        - OpenAI
        - OpenAI Compatible
        - OpenRouter
        - Requesty
        - Unbound
        - VS Code Language Model API
        - xAI (Grok)
        - Not Applicable / Other
    validations:
      required: true

  - type: input
    id: model
    attributes:
      label: Model Used
      description: Clearly specify the exact model (e.g., Claude 3.7 Sonnet), if you think the issue is related to the model you are using, be sure to fill in this field.


  - type: textarea
    id: what-happened
    attributes:
      label: Actual vs. Expected Behavior
      description: Clearly state what actually happened and what you expected instead.
      placeholder: Provide precise details of the issue here.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🔁 Steps to Reproduce
      description: |
        Help us see what you saw. Give clear, numbered steps:

        1. Setup (OS, extension version, settings)
        2. Exact actions (clicks, input, files, commands)
        3. What happened after each step

        Think like you're writing a recipe. Without this, we can't reproduce the issue.
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: 💥 Outcome Summary (Optional)
      description: |
        Recap what went wrong in one or two lines. Use this if the bug is weird, unexpected, or needs extra context.

        Example: "Expected code to run, but got an empty response and no error."
      placeholder: Expected ___, but got ___.

  - type: textarea
    id: logs
    attributes:
      label: 📄 Relevant Logs or Errors
      description: Paste API logs, terminal output, or errors here. Use triple backticks (```) for code formatting.
      render: shell